POST http://localhost:3000/Todos
Content-Type: aplication/json

{
        "id": ,
        "type": "study",
        "task": "Study Time",
        "streak": 5,
        "repeat": "5 days per week",
        "bgimageID": "studyBG",
        "description": "Sxxx"
}
