POST http://localhost:3000/todos
Content-Type: application/json

{
        "type": "study",
        "task": "Study Time",
        "streak": 5,
        "repeat": "5 days per week",
        "bgimageID": "studyBG",
        "description": "Sxxx"
}

