POST http://localhost:3000/Todos
Content-Type: aplication/json

{
        "id": 3,
        "type": "study",
        "task": "Study Time",
        "streak": 5,
        "repeat": "5 days per week",
        "bg-imageID": "studyBG",
}
